// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// editDist
int editDist(const std::string& s1, const std::string& s2);
RcppExport SEXP _risoma_editDist(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(editDist(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// findIsoforms
DataFrame findIsoforms(DataFrame mirnas, DataFrame reads, int maxEd5p, int maxEd3p);
RcppExport SEXP _risoma_findIsoforms(SEXP mirnasSEXP, SEXP readsSEXP, SEXP maxEd5pSEXP, SEXP maxEd3pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type mirnas(mirnasSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type reads(readsSEXP);
    Rcpp::traits::input_parameter< int >::type maxEd5p(maxEd5pSEXP);
    Rcpp::traits::input_parameter< int >::type maxEd3p(maxEd3pSEXP);
    rcpp_result_gen = Rcpp::wrap(findIsoforms(mirnas, reads, maxEd5p, maxEd3p));
    return rcpp_result_gen;
END_RCPP
}
// markDuplicates
DataFrame markDuplicates(std::string fqFile, int minReadNum);
RcppExport SEXP _risoma_markDuplicates(SEXP fqFileSEXP, SEXP minReadNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fqFile(fqFileSEXP);
    Rcpp::traits::input_parameter< int >::type minReadNum(minReadNumSEXP);
    rcpp_result_gen = Rcpp::wrap(markDuplicates(fqFile, minReadNum));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_risoma_editDist", (DL_FUNC) &_risoma_editDist, 2},
    {"_risoma_findIsoforms", (DL_FUNC) &_risoma_findIsoforms, 4},
    {"_risoma_markDuplicates", (DL_FUNC) &_risoma_markDuplicates, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_risoma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
