// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_edit_dist
int calc_edit_dist(const std::string& s1, const std::string& s2);
RcppExport SEXP _risoma_calc_edit_dist(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_edit_dist(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// find_isoforms
DataFrame find_isoforms(DataFrame mirnas, DataFrame reads, int max_ed_5p, int max_ed_3p);
RcppExport SEXP _risoma_find_isoforms(SEXP mirnasSEXP, SEXP readsSEXP, SEXP max_ed_5pSEXP, SEXP max_ed_3pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type mirnas(mirnasSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type reads(readsSEXP);
    Rcpp::traits::input_parameter< int >::type max_ed_5p(max_ed_5pSEXP);
    Rcpp::traits::input_parameter< int >::type max_ed_3p(max_ed_3pSEXP);
    rcpp_result_gen = Rcpp::wrap(find_isoforms(mirnas, reads, max_ed_5p, max_ed_3p));
    return rcpp_result_gen;
END_RCPP
}
// mark_duplicates
DataFrame mark_duplicates(std::string fq_file, int min_read_num);
RcppExport SEXP _risoma_mark_duplicates(SEXP fq_fileSEXP, SEXP min_read_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fq_file(fq_fileSEXP);
    Rcpp::traits::input_parameter< int >::type min_read_num(min_read_numSEXP);
    rcpp_result_gen = Rcpp::wrap(mark_duplicates(fq_file, min_read_num));
    return rcpp_result_gen;
END_RCPP
}
// mark_duplicates_gz
DataFrame mark_duplicates_gz(std::string fq_file, int min_read_num);
RcppExport SEXP _risoma_mark_duplicates_gz(SEXP fq_fileSEXP, SEXP min_read_numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fq_file(fq_fileSEXP);
    Rcpp::traits::input_parameter< int >::type min_read_num(min_read_numSEXP);
    rcpp_result_gen = Rcpp::wrap(mark_duplicates_gz(fq_file, min_read_num));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_risoma_calc_edit_dist", (DL_FUNC) &_risoma_calc_edit_dist, 2},
    {"_risoma_find_isoforms", (DL_FUNC) &_risoma_find_isoforms, 4},
    {"_risoma_mark_duplicates", (DL_FUNC) &_risoma_mark_duplicates, 2},
    {"_risoma_mark_duplicates_gz", (DL_FUNC) &_risoma_mark_duplicates_gz, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_risoma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
