# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the minimum number of edits to convert ‘s1‘ into ‘s2‘.
#'
#' @param s1 first string
#' @param s2 second string
#' @return edit distance
editDist <- function(s1, s2) {
    .Call(`_risoma_editDist`, s1, s2)
}

#' Find isoform from reads based on reference miRNAs
#'
#' @param mirnas a data.frame storing mature miRNA ID (matrue_ID),
#'   mature miRNA sequence (mature_seq), mature start (mature_start),
#'   seed on miRNA (seed_seq), precursor ID (pre_ID) and precursor sequence
#'   (pre_seq)
#' @param reads a data.frame containing sequence and it's amount
#' @param maxEd5p the maximum distance between 5’ region of reads with 
#'   reference miRNA
#' @param maxEd3p the maximum distance between 3' region of reads with 
#'   reference miRNA
#' @return a data.frame with columns: mature_ID, read_seq, read_num and dist
findIsoforms <- function(mirnas, reads, maxEd5p, maxEd3p) {
    .Call(`_risoma_findIsoforms`, mirnas, reads, maxEd5p, maxEd3p)
}

#' Mark duplicates in the FASTQ file
#'
#' To speed up the computation, we first extract sequences of each read and
#' then mark and count duplicates.
#'
#' @param fqFile FASTQ file of a sample
#' @param minReadNum the minimum read count for an isoform
#' @return a data.frame with column 'read_seq' and 'read_num'
markDuplicates <- function(fqFile, minReadNum) {
    .Call(`_risoma_markDuplicates`, fqFile, minReadNum)
}

