# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find the minimum number of edits to convert ‘s1‘ into ‘s2‘.
#'
#' @param s1 first string
#' @param s2 second string
#' @return edit distance
edit_dist <- function(s1, s2) {
    .Call(`_risoma_edit_dist`, s1, s2)
}

#' Find isoform from reads based on reference miRNAs
#'
#' @param mirnas A data.frame storing mature miRNA ID (matrue_id),
#'   mature miRNA sequence (mature_seq), mature start (mature_start),
#'   seed on miRNA (seed_seq), precursor ID (pre_id) and precursor sequence
#'   (pre_seq)
#' @param reads A data.frame containing sequence and it's amount
#' @param max_ed_5p the maximum distance between 5’ region of reads with reference miRNA
#' @param max_ed_3p the maximum distance between 3' region of reads with reference miRNA
#' @return a data.frame with columns: mature_id, read_seq, read_num and dist
find_isoforms <- function(mirnas, reads, max_ed_5p, max_ed_3p) {
    .Call(`_risoma_find_isoforms`, mirnas, reads, max_ed_5p, max_ed_3p)
}

#' Mark duplicates in the FASTQ file
#'
#' To speed up the computation, we first extract sequences of each read and
#' then mark and count duplicates.
#'
#' @param fq_file FASTQ file of a sample
#' @param min_read_num The minimum read count for an isoform
#' @return A data.frame with column 'read_seq' and 'read_num'
mark_duplicates <- function(fq_file, min_read_num) {
    .Call(`_risoma_mark_duplicates`, fq_file, min_read_num)
}

